[package]
name = "dircheck"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
clap = { version = "4.0", features = ["derive"] }
hex = "0.4"
md-5 = "0.10"
rusqlite = { version = "0.33", features = ["bundled"] }
tablestream = "0.1"
thiserror = "2.0"