[package]
name = "dircheck"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
clap = { version = "4.0", features = ["derive"] }
thiserror = "2.0"
rusqlite = { version = "0.33", features = ["bundled"] }
