[package]
name = "fspulse"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
clap = { version = "4.0", features = ["derive"] }
dirs = "6.0"
env_logger = "0.11"
hex = "0.4"
log = "0.4"
md-5 = "0.10"
rusqlite = { version = "0.33", features = ["bundled"] }
thiserror = "2.0"

tablestream = { git = "https://github.com/gtunes-dev/tablestream" }